"""add scores and score_price

Revision ID: 9f17ea999aa5
Revises: e416ef9adc51
Create Date: 2023-12-04 16:06:17.598268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f17ea999aa5'
down_revision: Union[str, None] = 'e416ef9adc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('scores', sa.Float(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('score_price', sa.Float(), server_default='102', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'score_price')
    op.drop_column('days', 'scores')
    # ### end Alembic commands ###
